baseurl = "https://makapx.github.io/makapx/"
theme = "hugo_theme_pickles"
languageCode = "it-IT"
Title = "The perks of being a sunflower"
# Copyright notice. This is displayer in the footer.
copyright = " "

# enable get info from git commits, such as file modification time.
# so we don't have to manually update it.
enableGitInfo = true

[params]
  paginate = 10
  custom_css = ["css/custom.css"]
  github = "makapx"
  author = "Martina Parlavecchio"
  avatar = "/images/avatar.jpg"
  #contact = "Your contact link (ex. mailto:foo@example.com)"
  bio = "Front-end web developer e studentessa di informatica. Attivista per i diritti animali. Femminista. Scrivo delle mie passioni e delle piccole cose della mia vita."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = " " 
  # Logo image. This is displayed ogp image.
  #logo = "/path/to/logo"
  #favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
